package uz.pdp.bot;

public interface BotState {
    String START = "START";
    String SHOW_ADMIN_MENU = "SHOW_ADMIN_MENU";
    String CATEGORY_CRUD = "CATEGORY_CRUD";
    String ADD_CATEGORY = "ADD_CATEGORY";
    String ADD_INNER_CATEGORY = "ADD_INNER_CATEGORY";
    String BOOK_CRUD = "BOOK_CRUD";
    String PAY_TYPE_CRUD = "PAY_TYPE_CRUD";
    String ORDER_STATUS_CRUD = "ORDER_STATUS_CRUD";
    String SHOW_ORDERS = "SHOW_ORDERS";
    String CHANGE_ORDER_STATUS = "CHANGE_ORDER_STATUS";
    String DOWNLOAD_ORDERS = "DOWNLOAD_ORDERS";
    String DOWNLOAD_USERS = "DOWNLOAD_USERS";

    String CHOOSE_LANG = "CHOOSE_LANG";
    String SHARE_CONTACT = "SHARE_CONTACT";
    String ENTER_CODE = "ENTER_CODE";
    String SHOW_MENU = "SHOW_MENU";
    String SHOW_BOOK_CATEGORY = "SHOW_BOOK_CATEGORY";
    String SHOW_BOOK_TYPE = "SHOW_BOOK_TYPE";
    String FILL_BALANCE = "FILL_BALANCE";
    String CHANGE_LANG = "CHANGE_LANG";
    String SHOW_BOOK = "SHOW_BOOK";
    String ENTER_PAGE = "ENTER_PAGE";
    String ENTER_AMOUNT = "ENTER_AMOUNT";
    String CHOOSE_PAY_TYPE = "CHOOSE_PAY_TYPE";
    String SHARE_LOCATION = "SHARE_LOCATION";
    String SHOW_BASKET = "SHOW_BASKET";
    String SHOW_PURCHASES = "SHOW_PURCHASES";
    String UPLOAD = "UPLOAD";
    String FINISH_ORDER = "FINISH_ORDER";
    String ABOUT_US = "ABOUT_US";
}
